### ISSUE TITLE
Smoother fan control

### ISSUE THREAD

**Issue by X0rg** [KostyaEsmukov/afancontrol#4]
Hello,

I own a Ryzen 5 3600X with schedutil CPU governor, but CPU temperature does spikes like every 5-7 seconds at idle.
This is a bit annoying because it generates random noise at idle.

Here is a diagram with 250 values:
![afancontrol](https://user-images.githubusercontent.com/2873785/87425366-cadac280-c5dd-11ea-85fc-c1f9e4fc18dd.png)

Archive with SVG digram and CSV file: [values.tar.gz](https://github.com/KostyaEsmukov/afancontrol/files/4918838/values.tar.gz)
afancontrol configuration file: [afancontrol.txt](https://github.com/KostyaEsmukov/afancontrol/files/4918772/afancontrol.txt)

Smoother fan control is welcome to correct this problem: I think afancontrol could use the mean of last umpteenth values instead of the current value.

**Comment by X0rg** [comment]
You are right, median will be more adequate than mean.

> Eventually I would love to have these filters implemented, but for the moment I don't have time to do that myself. Let me know if you would like to work on that yourself, so I could share what I have in that branch which could be a starting point.

I cannot guarantee that I will have free time to work on this, but if you don't mind, share your work in progress on a separate branch and I will take a look.

ATM, I set the CPU governor to *powersave* for low power tasks as a workaround.

**Comment by KostyaEsmukov** [comment]
I have just pushed that branch: https://github.com/KostyaEsmukov/afancontrol/tree/f/filters

IIRC it worked fine, but I just trashed the faulty HDD/SSD device instead of finishing that branch. :)

**Comment by KostyaEsmukov** [comment]
I have just released `afancontrol==2.2.0` which contains an initial support for filters: b06324c.

Example configuration:

```
[filter: moving_quantile_80]
type = moving_quantile
quantile = 0.8
window_size = 10

[temp:cpu]
...
filter = moving_quantile_80
```

`quantile = 0.8` would make it prefer higher temperatures (i.e. it would always take the 80-th percentile temperature in the window of last 10 observations). If the goal is to make fans more quiet at the cost of slower reaction, then a lower quantile can be used, such as `quantile = 0.3`.

**Comment by KostyaEsmukov** [comment]
This graph shows how the aforementioned `moving_quantile_80` filter affects the temperature measurements on Ryzen 3900X:

<img width="1417" alt="Screenshot 2020-09-29 at 01 52 12" src="https://user-images.githubusercontent.com/2418596/94493883-816e3c80-01f6-11eb-997e-b0a83b07ca02.png">

**Comment by X0rg** [comment]
(Sorry for the late response)

Wow, awesome, that is better now. Thank you very much!
