### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by phil21** [KostyaEsmukov/afancontrol#6]
Hello,

This certainly is no bug report.  I just wanted to say I had a simple problem (3 PWM controlled fans I wanted to tie to a different temp sensor than they were tied to on the motherboard) -  I was about to write a script for it until I thought of all the annoying edge cases.

I then googled and am very happy to have found afancontrol - simple, does precisely what I need, and I had it configured from your great documentation within 10 minutes or less working wonderfully.

Being adjacent to open source projects I certainly know it gets old only seeing problems users have - so I wanted to drop a note to say that this software saved me at minimum hours of my time, and made my life considerably easier.

Thanks and keep up the great work!

**Comment by KostyaEsmukov** [comment]
Thank you, Phil, for your kind words, I appreciate it very much. ❤️
